### ISSUE TITLE
[Improvement]: For a Mixed Hive-Arctic table format, when I grant permissions to the Hive table, I would like to also grant permissions to the Arctic table

### ISSUE THREAD

**Issue by nicochen** [apache/amoro#1307]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

For a Mixed Hive partitioned table, the Hive Table Location points to the Arctic Table Location + /hive. In this case, when I grant permissions to the Hive table, I can only grant permissions to the /hive directory, and not to the /change or /base directories.

For a Mixed Hive non-partitioned table, the Hive Table Location points to the Arctic Table Location + /hive + /{timestamp}+{txid}. In this case, when I grant permissions to the Hive table, I can only grant permissions to the aforementioned directories, and not to other directories.

### How should we improve?

For a Mixed Hive Arctic table format, when I grant permissions to the Hive table, I would like to also grant permissions to the Arctic table.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by baiyangtx** [comment]
Thanks for your issue.  
From your description it's more like a problem of path permissions but table premissions.  Can I understand this question like this your want the `/base` and `/change` path under the `/hive` path so you can reuse some grant tools base on Hive?  What you want is if you grant the path premission of hive table location, all mixed-hive table paths are granted.
