### ISSUE TITLE
[Subtask]: Do not store table metadata in AMS for MIXED-HIVE

### ISSUE THREAD

**Issue by baiyangtx** [apache/amoro#1337]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### Description

- load mixed-hive table without ams

### Parent issue

[#1061 ](https://github.com/NetEase/arctic/issues/1061)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Closed by #2691
