### ISSUE TITLE
[Subtask][Trino]: Support UnifiedCatalog in Trino Engine. 

### ISSUE THREAD

**Issue by baiyangtx** [apache/amoro#1343]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### Parent issue

https://github.com/NetEase/arctic/issues/1061

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Closed as not planned.
