### ISSUE TITLE
[Feature]: Provide standard SQL management instructions and command-line tools

### ISSUE THREAD

**Issue by zhoujinsong** [apache/amoro#1357]
### Description

Currently, different management instructions are provided for different table formats in different engines. In order to provide a plug-and-play data lake experience, we need to provide a set of standard and unified management instructions and their corresponding command-line tools.

### Use case/motivation

Provide standard SQL management instructions and command-line tools so that users can use it to manage all data lake tables with unified commands.

### Describe the solution

- Provide standard SQL access methods, such as MySQL protocol.
- Provide a set of standard table management statements, including viewing, creating, modifying, and deleting tables.
- Provide a set of standard monitoring commands to view various states of the table.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shendanfengg** [comment]
For standard SQL, we need to support the "SHOW CREATE TABLE" syntax, which is not yet supported in version 041.

**Comment by baiyangtx** [comment]
> For standard SQL, we need to support the "SHOW CREATE TABLE" syntax, which is not yet supported in version 041.

Why do we need SQL like this? The standard SQL maybe not a spark sql and not run in spark engine.
