### ISSUE TITLE
[Feature]: Add metric collection for ams

### ISSUE THREAD

**Issue by hameizi** [apache/amoro#1528]
### Description

We will add metric collection for AMS to provide more metrics to describe the states of tables and optimizer, among others.

### Describe the solution

https://docs.google.com/document/d/1FS3yskgiZCH2WQkLyOTvtMX6RcakgzyzzooQ31wGdNI/edit#

### Subtasks

**Metric Framework**
- [x] #1765

**Metric Collection**
- #1766
- #1769 
- https://github.com/NetEase/amoro/issues/2495

**Metric Reporter**

- https://github.com/NetEase/amoro/issues/2494

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shidayang** [comment]
@zhongqishang cc

**Comment by zhoujinsong** [comment]
Close as completed.
