### ISSUE TITLE
[Improvement]: The `create_time` of `task_runtime` is useless now

### ISSUE THREAD

**Issue by wangtaohz** [apache/amoro#1637]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

I found the `create_time` of `task_runtime` is always null.
<img width="1057" alt="image" src="https://github.com/NetEase/arctic/assets/103108928/cd10d078-523b-4f89-a496-faecc241f5d7">

### How should we improve?

We should remove the column `create_time` from the table `task_runtime`, or add a field `long createTime` for the class `TaskRuntime`.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Can we indirectly obtain the creation time of the task through `table_optimizing_process.plan_time`? Also, the creation time of the task seems to have no special use at the moment. If that's the case, I suggest removing this field from the table structure first.

**Comment by wangtaohz** [comment]
> Can we indirectly obtain the creation time of the task through `table_optimizing_process.plan_time`?

Yes, the creation time of all tasks should be equal to the `table_optimizing_process.plan_time`, so there is no need to save the creation time separately for each task.
