### ISSUE TITLE
[Improvement]: Reduce useless log for github ci

### ISSUE THREAD

**Issue by baiyangtx** [apache/amoro#1714]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Too many ci logs, and we can't view the fail reason in GitHub action pages. We have to download the log archive file.

### How should we improve?

Set log level to WARN when executing github ci.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangtaohz** [comment]
The warn/error message is enough for troubleshooting, like

<img width="1643" alt="image" src="https://github.com/NetEase/arctic/assets/103108928/23dd0485-51ac-4502-ac5d-b82e94893bfd">
