### ISSUE TITLE
[Improvement]: Improvement Flink batch mode usage by removing /*+ OPTIONS('streaming'='false') */ and supporting both primary and non-primary key tables

### ISSUE THREAD

**Issue by XiaoGerGer** [apache/amoro#1715]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently arctic does not have a way to automatically adapt to flink execution mode, so when in execution.runtime-mode=batch mode, you need to write the following sql:

```sql
select * from table /*+ OPTIONS('streaming'='false') */
```

But we expect to be able to directly write the following sql (whether primary key table, non-primary key table, partition table, ordinary table ...) :

```sql
select * from table
```

Because in batch mode, streaming always equals false.

Also, if execution.runtime-mode=streaming, streaming defaults to true, but the user can still change it to false by hint.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Automatically determining the read mode based on the running mode of the Flink job is indeed a good optimization. If the solution is feasible, I think we should optimize it as soon as possible.

How do you think? @YesOrNo828 @lklhdu

**Comment by lklhdu** [comment]
> Automatically determining the read mode based on the running mode of the Flink job is indeed a good optimization. If the solution is feasible, I think we should optimize it as soon as possible.
> 
> How do you think? @YesOrNo828 @lklhdu

I will follow this issue.

**Comment by zhoujinsong** [comment]
> > Automatically determining the read mode based on the running mode of the Flink job is indeed a good optimization. If the solution is feasible, I think we should optimize it as soon as possible.
> > How do you think? @YesOrNo828 @lklhdu
> 
> I will follow this issue.

I think we can discuss the implementation plan here first, and then develop it to allow more interested people to contribute to this feature.
