### ISSUE TITLE
[Bug]: Throw NPE during restarting AMS

### ISSUE THREAD

**Issue by XBaith** [apache/amoro#1762]
### What happened?

If SQL session had closed when execute multiple SQL operations in one transaction, the process id may only persistence in databse `table_runtime`, but not in others(table_optimizing_process, task_runtime). The status of optimzing will block in `RUNNING`, so we have to clear them in the database and restart AMS. but AMS will not load any task based on the process id that exists only in the table meta, so an exception will occur.

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### How to reproduce

1. only persistence process id in table_runtime and update optimzing status as Running
2. restart AMS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wangtaohz** [comment]
> If SQL session had closed when execute multiple SQL operations in one transaction, the process id may only persistence in databse table_runtime, but not in others(table_optimizing_process, task_runtime)

I think we should use `Transaction` to avoid the non-atomic operation, rather than fixing abnormal states after starting AMS.

**Comment by XBaith** [comment]
> I think we should use `Transaction` to avoid the non-atomic operation, rather than fixing abnormal states after starting AMS.

I agree, but sometimes the state of the optimizating process goes wrong due to unexpected errors and we have to clean up the records in the database and restart AMS. On the other hand, I think it would be nice to enhance the robustness of AMS

**Comment by wangtaohz** [comment]
A more specific example of "unexpected errors" would help us better understand the necessity of doing so.

**Comment by XBaith** [comment]
> A more specific example of "unexpected errors" would help us better understand the necessity of doing so.

 I'd like to keep transaction first, but the system doesn't always run as we expect. I fount some errors make the state of process not correct or have to clean up and restart: 
- Only update `table_runtime` when start executing process, `table_optimizing_process` and `table_runtime` should be update or insert but it was not.
- Those tables that are hard to rewrite block other pending tables. So I tried to stop the optimization by cleaning up the records. I know this is not a good solution and should be fixed by closing the process with `self-optimizing` disabled.
These issues need to be fixed by other PRs, the current PR just improve the robustness of the system and prevent other users from having this problem with another unfixed version

**Comment by zhoujinsong** [comment]
I think it's necessary to do more checks on recovered metadata during initialization.

However, I'm more concerned about the problem of inconsistent metadata. We should try to reproduce it, identify the cause of the problem, and fix it.
