### ISSUE TITLE
[Subtask]: Implement table self-optimizing metric collection

### ISSUE THREAD

**Issue by hameizi** [apache/amoro#1766]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### Description

Implement table self-optimizing metric collection

Design:   https://docs.google.com/document/d/1PL2Dbcd3ChnXo8872ffzgoGYYX7CO7qSUWXc5rYO4MU/edit#heading=h.4boepjbyxjk7

### Parent issue

#1528 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by huyuanfeng2018** [comment]
I can try this, plz Assignees me
