### ISSUE TITLE
[Improvement]: Clarify the concept of watermark and optimize its implementation

### ISSUE THREAD

**Issue by zhoujinsong** [apache/amoro#1805]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

We have implemented calculating and showing the watermark for Mixed format tables.

As #944 discusses, the current implementation has some issues that should be fixed.

In addition, as we support more table formats, we should consider better ways to support the watermark on other format tables.

### How should we improve?

- Clarify the concept of table watermark to support it on all table formats.
- Improve the implementation of table watermark on Mixed formats.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Before starting the improvement, I would like to collect some information about table watermark.

**What is table  watermark?**

A watermark is a time-based property on a table that indicates the freshness of the table, indicating that data older than this time has already been written to the table.

**What is the usage of table watermark?**

- As a metric on the table, it enables users to perceive the freshness of the data on the table.
- In a batch workflow, it serves as the basis for determining whether downstream tasks should be triggered for computation.
- Foundational concepts for other features, such as automatically generating tags based on watermark.

**How to generate table watermark**

The watermark changes as data is written, so it is usually generated and recorded in the table ingestion job. It is generally only generated in streaming ingestion jobs as It is difficult to ensure the semantic meaning of watermark in batch write jobs.

Here are some implementation methods of different table formats:

- Paimon: based on Flink watermark, merged.
- Iceberg: based on Flink watermark, not merged(https://github.com/apache/iceberg/pull/6253).
- Hudi: based on Flink watermark, not merged(https://github.com/apache/hudi/pull/8753).

**Comment by majin1102** [comment]
It seems that the Iceberg community has discussed watermark quite further.  I made some conclusions:

1. Watermark of a table(Iceberg or others) in many cases should be a property or metric based on a timestamp column of this very table, which is defined as `event-time` column in Mixed Iceberg format. instead of reported from an upstream streaming job. Two scenarios should be considered:
    1. For a Flink job with watermark writing to a table, the watermark could reveal the real event time of the sink table, that's how Paimon watermark works, but this watermark could somehow be conflicted with the event time defined by user.
    2. For a Table defined with event time(means watermark is necessary), there could not be any streaming job writing to the table, or it's not guaranteed that streaming jobs will always define a watermark.
    3. Given the two points above, we may need to support  both defining event time on a table and using watermark values from streaming jobs. If user explicitly defines event time on a table, the watermark is calculated based on the data distribution of that column during committing. If event time is not defined, the watermark values from streaming jobs could be used. If neither is defined, the commit time can be considered. 
    
2. There could be multiple streaming jobs writing to a table, the watermark must align all streaming writers, which means that  calculating the watermark in committing phase is not a feasible solution.  Amoro could calculate watermark values in refreshing phase and define an IDLE timeout like Flink dealing with multiple datastreams.

**Comment by huyuanfeng2018** [comment]
> 2\.  Amoro could calculate watermark values in refreshing phase and define an IDLE timeout like Flink dealing with multiple datastreams.
