### ISSUE TITLE
[Bug]: Setting comment to a field of type timestamp when building a table with Terminal or Spark does not work.

### ISSUE THREAD

**Issue by nicochen** [apache/amoro#1806]
### What happened?

When I created the table and set a comment in the timestamp field it didn't work, my ddl for the table was as follows
```
create table arctic.arctic_test_timestamp (
    id int comment 'test_id',
    name string, 
    ts timestamp comment 'test_timestamp',
    primary key (id)
) using arctic 
tblproperties ('table.props' = 'val');
```
![image](https://github.com/NetEase/amoro/assets/4648576/f3cbcdaf-33e8-4c84-993c-ceb134b74b9d)

### Affects Versions

master

### What engines are you seeing the problem on?

Spark

### How to reproduce

1.Craete table use terminal and set comment to a field of type timestamp.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baiyangtx** [comment]
This is an iceberg bug, and fixed in this PR https://github.com/apache/iceberg/pull/8416, and will be released in 1.4.

Upgrade iceberg version to 1.4 will fix this.
