### ISSUE TITLE
[Improvement]: Optimize the commit process of commit snapshots for UnKeyedTable optimizing

### ISSUE THREAD

**Issue by hameizi** [apache/amoro#1835]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Before version 1.3.x of Iceberg, the RewriteFiles interface did not provide methods for specifying sequence numbers while adding and deleting delete files. Therefore, in UnKeyedTableCommit, we had to complete table rewrite through transactional submission and an additional snapshot of deleting files. However, Iceberg version 1.3.x provides a more flexible interface design to improve this, and we can complete the rewrite in one submission through the following approach:
```
RewriteFiles dataFileRewrite = icebergTable.newRewrite();
addDeleteFiles.forEach(dataFileRewrite::addFile);
removedDataFiles.forEach(dataFileRewrite::deleteFile);
addDeleteFiles.forEach(dataFileRewrite::addFile);
removedDeleteFiles.forEach(dataFileRewrite::deleteFile);
dataFileRewrite.dataSequenceNumber(sequenceNumber);
dataFileRewrite.commit();
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hameizi** [comment]
cc @861752346

**Comment by tcodehuber** [comment]
This issue has not be resolved, right? 
![image](https://github.com/NetEase/amoro/assets/5411862/cd7028e9-02a2-4000-aa85-19aee71bddf1)
