### ISSUE TITLE
[Improvement]: Improve plan speed for partitions with only datafile files

### ISSUE THREAD

**Issue by huyuanfeng2018** [apache/amoro#1838]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

When we need to plan a table before optimizing, this happens in the optimizer pull phase, but it seems that it is currently in a serial way, so there will be some problems:

When the parallelism of my `optimizer` is high enough, the serial single-threaded plan will become the bottleneck of the entire resource group, and there are often a lot of pending tables at the same time, but my optimizer is very idle because they are waiting for ams plan.

So we should try to do some optimization on the plan stage

### How should we improve?

1. I found that the most time-consuming phase of the plan phase is the acquisition of `sequenceNumber`, which is an io-intensive operation, so whether the plan phase can be parallelized to improve efficiency?
2. If a partition is in append only mode, can you skip the acquisition of sequenceNumber, because iceberg should only use sequenceNumber when merging partitions with `delete-file`,  like this:
```
    if (deleteFiles.size() > 0) {
      dataFile = createDataFile(task.file());
    } else {
      dataFile = createDataFileWithoutSequenceNumber(task.file())
      }

  private IcebergDataFile createDataFileWithoutSequenceNumber(DataFile dataFile) {
    return new IcebergDataFile(dataFile, -1);
  }
```
but not sure if it will cause other problems

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
@huyuanfeng2018 
Thanks for bringing up this improvement.

I have also noticed the optimizing planning bottleneck issue too.
And @majin1102 is pushing for an improvement in the planning bottleneck issue within a group. He will share his idea when it is ready.

Regarding the improvement you mentioned, there is a related task #1839  that will remove the sequence number fetching process, which will greatly improve the efficiency of optimizing planning.

**Comment by huyuanfeng2018** [comment]
> @huyuanfeng2018 Thanks for bringing up this improvement.
> 
> I have also noticed the optimizing planning bottleneck issue too. And @majin1102 is pushing for an improvement in the planning bottleneck issue within a group. He will share his idea when it is ready.
> 
> Regarding the improvement you mentioned, there is a related task #1839 that will remove the sequence number fetching process, which will greatly improve the efficiency of optimizing planning.

Hmm, looks like #1839 is a better solution
