### ISSUE TITLE
[Feature]: Support Deploying Flink optimizer to Kubernetes cluster

### ISSUE THREAD

**Issue by zhoujinsong** [apache/amoro#1856]
### Description

For now, Amoro support deploying Flink optimizer to the Yarn cluster only.
We should support deploying it to the Kubernetes cluster too.

### Use case/motivation

Support configuring K8s cluster information in FlinkContainer, and then scheduling Flink Optimizer on the K8s cluster.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by czy006** [comment]
#2695
