### ISSUE TITLE
[Improvement]: Make the front-end data presentation more user-friendly.

### ISSUE THREAD

**Issue by FourSpaces** [apache/amoro#1934]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

1、The query result of data should not be omitted
![image](https://github.com/NetEase/amoro/assets/13359726/7690ad43-33fb-49ef-8e73-890f8f2e7a76)
 
2、The tips message will automatically close after a period of time or can be closed manually
![image](https://github.com/NetEase/amoro/assets/13359726/c5c6856d-605b-44ef-b53f-72cf6c5a8f35)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangtaohz** [comment]
<img width="807" alt="image" src="https://github.com/NetEase/amoro/assets/103108928/545e6871-e752-4e01-aaf6-ea8f7a3686e9">

As a temporary solution, you can click three times here and ctrl+c to select and copy the full content.

**Comment by baiyangtx** [comment]
@minteliuwm Are you interested in this to fix it?
