### ISSUE TITLE
[Improvement]: The Transaction page displays all snapshots as well as the producer of each snapshot

### ISSUE THREAD

**Issue by wangtaohz** [apache/amoro#1971]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, the Transaction page ignores the snapshots generated by optimizing and only displays the snapshots written by users, and this design has some adverse effects.

For the **current** functionality, hiding the snapshots generated by optimizing cannot reflect the actual changes on the table, including:

1. The current snapshot cannot reflect the latest state of the table.

2. Can't view the information about optimizing commits (such as snapshot summary) and the order of commits with other commits. Sometimes it is also useful to confirm whether optimizing commits have been successful from here.

3. If after expiring snapshots, only the snapshots generated by optimizing are left, the transaction page will be empty.

For **future** functionality, it also brings some limitations:

1. It affects the display of **Tags and Branches**. Tags and branches may appear on any snapshot, including those generated by optimizing.

2. It affects support for **Time Travel**. Performing time travel on snapshots after optimizing will bring performance benefits to queries.

3. It affects support for **Rollback**. Rollback to the snapshots generated by optimizing should also be supported.

### How should we improve?

1. Display all snapshots on the Transaction Page.
2. Add a column `Producer` to display the producer of the snapshot, like `OPTIMIZE` `INGESTION`.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by majin1102** [comment]
If this happens, is optimized page, all other extended pages(like expire, clean processes) would be unnecessary.

From my view, transaction should be considered as user action, any processes which do not involve data change shouldn't belong to transactions. Think about database like MySQL. If it is necessary to showcase these commits in somewhere, consider displaying them on the optimized page or process related pages?

**Comment by wangtaohz** [comment]
Thank you for sharing your thoughts. While I agree that processes that do not involve data change may not necessarily belong to transactions, I believe that displaying all snapshots on the `Transactions` page is still necessary for a complete historical view of the table.

As I mentioned earlier, Amoro currently lacks the ability to display complete historical snapshots, and this functionality serves as the basis for features such as Time Travel, Rollback, Tags, and Branches. While displaying snapshots on the  process-related pages(like `Optimizing` page) may be useful, it does not provide a comprehensive view of the table's historical state.

Therefore, I still believe that transforming the `Transactions` page into a `Snapshots` page is the best solution to address this issue and provide users with a complete historical view of the table. This way, the `Transactions` page will be categorized under state-related information, while other process-related pages (like `Optimizing`, `Operations`) will remain unchanged.

I hope this explanation clarifies my viewpoint, and I will provide a more detailed design.
