### ISSUE TITLE
[Improvement]: AMS frequently print warning logs of 'Unclosed ResolvingFileIO'

### ISSUE THREAD

**Issue by wangtaohz** [apache/amoro#2024]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?
 When Table and FileIO objects in AMS are cleaned up by garbage collection, an warning log will be printed.

<img width="1127" alt="image" src="https://github.com/NetEase/amoro/assets/103108928/ca2b2a39-5268-4f40-a400-8441d19a96c7">

### How should we improve?

Close the FileIO after using it or ignore the logs

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangtaohz** [comment]
As a temporary solution, we can add the following configuration to the `conf/log4j.xml` of AMS.

```
    <Loggers>
        ...
        ...

        <!-- close the WARN logs of org.apache.iceberg.io.ResolvingFileIO -->
        <Logger name="org.apache.iceberg.io.ResolvingFileIO" level="error" additivity="false">
            <AppenderRef ref="infoFileAppender"/>
        </Logger>

        ...
        ...
    </Loggers>
```

**Comment by baiyangtx** [comment]
Maybe we should close the fileIo ASAP ?
