### ISSUE TITLE
[Feature]: Support mixed-format table scan by time traveling via FlinkSQL

### ISSUE THREAD

**Issue by YesOrNo828** [apache/amoro#2181]
### Description

--use timestamp constant expression
SELECT * FROM amoro_tbl FOR SYSTEM_TIME AS OF TIMESTAMP '2023-07-31 00:00:00'

--use expression with functions that can be reduced to a timestamp constant
SELECT * FROM amoro_tbl FOR SYSTEM_TIME AS OF TIMESTAMP '2023-07-31 00:00:00' - INTERVAL '1' DAY

### Use case/motivation

The Time Travel Query feature is already supported for Flink 1.18 SQL.

A time travel query could scan the snapshot of the mixed table in batch mode.

### Describe the solution

- time travel requires the corresponding catalog that the table belongs to implementing the getTable(ObjectPath tablePath, long timestamp) 
- Also requires the DynamicTableSourceFactory to create a table source of the snapshot.

```java
public class MyDynamicTableFactory implements DynamicTableSourceFactory {
    @Override
    public DynamicTableSource createDynamicTableSource(Context context) {
        final ReadableConfig configuration =
                Configuration.fromMap(context.getCatalogTable().getOptions());

        // Get a snapshot from CatalogTable
        final Optional<Long> snapshot = context.getCatalogTable().getSnapshot();

        // Build DynamicTableSource using snapshot options.
        final DynamicTableSource dynamicTableSource = buildDynamicSource(configuration, snapshot);

        return dynamicTableSource;
    }
}
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by czy006** [comment]
Perhaps in the future iceberg 1.5.x version will support Flink 1.18 and we can carry out this work.
