### ISSUE TITLE
[Bug]:  Spark terminal don't support write paimon under hadoop2.x for spark3.1

### ISSUE THREAD

**Issue by xieyi888** [apache/amoro#2355]
### What happened?

Paimon spark writer only support spark 3.2+
Amoro-Spark terminal version is 3.1.2  when build with hadoop 2.x

### Affects Versions

master/0.6.x

### What engines are you seeing the problem on?

AMS

### How to reproduce

build with hadoop2
``` 
mvn clean package -DskipTests -pl '!trino' -Dhadoop=v2
```

write into Paimon on ams terminal
![image](https://github.com/NetEase/amoro/assets/105206850/2e7340e0-1bbc-492a-a583-0196a1c0e20f)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xieyi888** [comment]
Do we consider upgrade spark version for hadoop2.x

**Comment by baiyangtx** [comment]
Spark write for Paimon required version spark 3.2+.
