### ISSUE TITLE
[Improvement]: For Mixed-Hive tables, default refresh time for Hive partitions should be configured

### ISSUE THREAD

**Issue by shendanfengg** [apache/amoro#2391]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

![image](https://github.com/NetEase/amoro/assets/109209550/ef528236-4bb8-4ee4-8fa0-7a7e57a741d1)
As shown in the figure, our default configuration is -1, which may result in Full Self-Optimizing not being executed for some Mixed Hive table history partitions. 

### How should we improve?

Set a default value for this configuration

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by majin1102** [comment]
> @shendanfengg I saw you trying to change the default value of `base.hive.refresh-interval` in order to refresh the data in Hive for all Mixed-Hive format tables every half an hour by default.
> 
> This configuration was initially disabled because we couldn't ensure that all users of Mixed-Hive format tables have this requirement. Can you adjust the default configuration under Catalog to enable this feature for all your Mixed-Hive tables instead of directly changing the default value of this configuration? I still can't confirm that all users of Mixed-Hive format tables have this requirement.

Hi, danfeng, please check the comment in releated PR
