### ISSUE TITLE
[Improvement]: More detail for table metrics

### ISSUE THREAD

**Issue by zhongqishang** [apache/amoro#2400]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

![image](https://github.com/NetEase/amoro/assets/16421989/b8769716-217d-4601-9329-2d2c95648ae3)

![image](https://github.com/NetEase/amoro/assets/16421989/c1ee187d-246a-4723-8761-d5250bcb18c7)

Current Base table metric only have `File count`/ `Total size` / `Average File Size`
Statistics are mixed data file and delete file.

### How should we improve?

- Add Average Data File Size
- Data file / eq delete file / pos delete file count separately
- Add eq delete count ratio for data count
- Add pos delete count ratio for data count

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangtaohz** [comment]
There are many details to consider.
1. separate parameter designs may be necessary for different Table Formats.
2. when users are using the Iceberg Table in an append scenario, there are no delete files, so it's better not to display delete-related metrics at that time.
3. Change Store and Base Store of Mixed Format also need separate designs

BTW, we can access these detailed metrics information on the snapshots page.

<img width="981" alt="image" src="https://github.com/NetEase/amoro/assets/103108928/aea6d634-cfa7-4671-b717-ebee3fc4e313">

**Comment by wangtaohz** [comment]
> Add eq delete count ratio for data count
Add pos delete count ratio for data count

@zhongqishang I'm a little curious about the real requirements for displaying these ratios :)
