### ISSUE TITLE
[Improvement]: The values of the vertical axis are partially hidden in the chart of the Table Snapshots Page  

### ISSUE THREAD

**Issue by wangtaohz** [apache/amoro#2444]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

<img width="1245" alt="image" src="https://github.com/NetEase/amoro/assets/103108928/83bd63bd-a148-44aa-8fa9-45c24831979e">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chouchouji** [comment]
I will submit a pull request to solve it
