### ISSUE TITLE
[Subtask]: Automatically create tags on snapshots for Mixed Iceberg Format

### ISSUE THREAD

**Issue by wangtaohz** [apache/amoro#2487]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### Description

Automatically generate tags on a snapshot based on watermarks to help users achieve longer time travel by retaining a small number of snapshots.

We should support this feature for the Mixed Format Table

### Parent issue

- #1354

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Closed as not planned.
