### ISSUE TITLE
[Subtask]: Table refresh metric collection

### ISSUE THREAD

**Issue by baiyangtx** [apache/amoro#2495]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### Description

Table Refresh metric design and implement.

### Parent issue

#1528

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Close as not planed.
