### ISSUE TITLE
[Bug]: Optimization process suspended in RUNNING state

### ISSUE THREAD

**Issue by XBaith** [apache/amoro#2507]
### What happened?

A process contains multiple tasks, but according to the AMS log the optimizer was not polling some of them, causing the process to hang
### Affects Versions

master

### What engines are you seeing the problem on?

There are two Flink Optimizers

### Relevant log output

![image](https://github.com/NetEase/amoro/assets/54210725/586c0fec-3d72-49e4-bf90-5cbfd923a639)

### Anything else

![image](https://github.com/NetEase/amoro/assets/54210725/1b532ee0-5bdd-4dd8-8a8d-d84b1388bd30)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
@XBaith Is there any new information or progress about this issue?
