### ISSUE TITLE
[Improvement]: Refact building shuffle policy in  flink sink connector with SPI, making it more flexible and pluggable

### ISSUE THREAD

**Issue by nicochen** [apache/amoro#2545]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

At present,  amoro flink connectors only use one class ‘RoundRobinShuffleRulePolicy’ to implement different shuffle policies such as non\keyed hash\ partitioned hash. The code could be refactor to improve the readability. Most importantly,  other (customised) shuffle policies（e.g range, load balanced）can be supported  easily  in the future by , for example, configuration  instead of hard coding.

### How should we improve?

We can use java SPI to dynamically load shuffle policies.  It is achieved by simply adding shuffle policy implementation to application and configure shuffle policy factory in service configuration files , this  definitely follows the implementation of flink table factory. 

Then, developers can contribute their own shuffle policies based on this service framework. For me, it may be a load balanced  shuffle policy.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by nicochen** [comment]
@zhoujinsong any idea on this topic?

**Comment by huyuanfeng2018** [comment]
In fact, the sink in the iceberg community has improvements for shuffle. if use a spi mechanism, which may be difficult. In iceberg's design, a flink operator needs to be added to collect statistical information.
https://github.com/apache/iceberg/issues/6303
