### ISSUE TITLE
[Subtask]: Validate the compatibility of Amoro with Hive 4.0 and provide support for Hive 4.0

### ISSUE THREAD

**Issue by zhoujinsong** [apache/amoro#2574]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### Description

As the Hive-4.0.0-beta-1 is already available and soon there will be a GA. Amoro should validate the compatibility with it and support Hive 4.0 as soon as the GA is published.

### Parent issue

#2564

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by czy006** [comment]
https://github.com/apache/hive/releases/tag/rel%2Frelease-4.0.0
