### ISSUE TITLE
[Feature]: Add amoro-shaded project

### ISSUE THREAD

**Issue by klion26** [apache/amoro#2628]
### Description

Add amoro-shaded project (guava, jackson etc)

### Subtasks

- [x] #2719 
- [x] #2718 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
@klion26 Thanks a lot for driving this.
I created a separate repository for the shade project:https://github.com/apache/incubator-amoro-shade.

**Comment by klion26** [comment]
@zhoujinsong thanks for creating the project, will add the shaded project later.

**Comment by klion26** [comment]
@zhoujinsong Seems we can't file a pr to an empty project, could please init the shade project? thanks.

**Comment by zhongqishang** [comment]
@klion26 I have initialized it, can you try again?

**Comment by klion26** [comment]
@zhongqishang thanks for the effort, will try it later.

**Comment by klion26** [comment]
This has been resolved in [incubator-amoro-shade](https://github.com/apache/incubator-amoro-shade). repo, close it now
