### ISSUE TITLE
[Bug]: Expand icon doesn't work in optimizing tab

### ISSUE THREAD

**Issue by XBaith** [apache/amoro#2660]
### What happened?

Do not display any information after clicking expand icon

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### Anything else

![image](https://github.com/NetEase/amoro/assets/54210725/35393034-2b18-4193-9e0f-94810903693b)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhangmo8** [comment]
#2668 maybe this is helpful
