### ISSUE TITLE
[Feature]: Supporting RocketMQ as a new type for Logstore

### ISSUE THREAD

**Issue by zhoujinsong** [apache/amoro#267]
### Description

Supporting RocketMQ as a new type for Logstore

### Use case/motivation

Arctic support Kafka as its Logstore type only now.
We should support RocketMQ too.

### Describe the solution

- Support read and write data to RocketMQ as arctic tables's Logstore

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yiduwangkai** [comment]
i want to do it, please assign this ticket to me
