### ISSUE TITLE
[Improvement]: Display more details in the page of Optimizing->Optimizers

### ISSUE THREAD

**Issue by tcodehuber** [apache/amoro#2698]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Now there are only a few of columns displaying in the Tab of Optimizing->Optimizers. IMO, we can show more columns(startTime, touchTime, jobJd etc.) to distinguish  the optimizers. 
![image](https://github.com/apache/incubator-amoro/assets/5411862/0e744654-1ee9-44bf-897f-419aee91cf04)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by XBaith** [comment]
Hi @tcodehuber , Consider displaying the optimizer token id on the page so that we can identifier the different optimizer

**Comment by tcodehuber** [comment]
@XBaith JobId(Optimizer Id) usually contains resourceid. Can it be considered as identifier for different optimizers?

![image](https://github.com/apache/incubator-amoro/assets/5411862/0bd67a4c-352b-47ee-93f0-a1c67961ce4d)

**Comment by XBaith** [comment]
> @XBaith JobId(Optimizer Id) usually contains resourceid. Can it be considered as identifier for different optimizers?

In some scenarios, the resouceid is empty or just a subindex, which I don't think is clear enough

**Comment by tcodehuber** [comment]
![image](https://github.com/apache/incubator-amoro/assets/5411862/9a59d88f-b68e-4409-88a5-27b4b6b9c6dd)

**Comment by baiyangtx** [comment]
I think it is useful that OptimizerId can distinguish between different optimizer instances, but for Token and Touch Time, it should be used more often to locate the problem, does this need to be displayed on the frontend?

Also, when there is an optimizerId to distinguish between different optimizer instances, it should be possible to cancel the order column, which has no practical meaning.

**Comment by tcodehuber** [comment]
> I think it is useful that OptimizerId can distinguish between different optimizer instances, but for Token and Touch Time, it should be used more often to locate the problem, does this need to be displayed on the frontend?
> 
> Also, when there is an optimizerId to distinguish between different optimizer instances, it should be possible to cancel the order column, which has no practical meaning.

Yes, i agree with discarding the order column. Furthermore, touchTime can be used as the active state for users.

**Comment by tcodehuber** [comment]
@baiyangtx @XBaith Can we discuss whether displaying the `Token` column in the frontend?

**Comment by baiyangtx** [comment]
> Can we discuss whether displaying the `Token` column in the frontend?

Is it really necessary to display the token on the frontend, and in what scenarios do you need to know this value?  @XBaith 

>  Furthermore, touchTime can be used as the active state for users.

If the optimizer is not active, it will disappear from frontend.

**Comment by zhoujinsong** [comment]
@tcodehuber @baiyangtx @XBaith 
Have we reached a consensus on what content needs to be added to the page?

**Comment by tcodehuber** [comment]
In my opinion, we can remove token from the frontend.

**Comment by XBaith** [comment]
> If the optimizer is not active, it will disappear from frontend.

Disply the token id can help us to identifier status of optimzier.  It would be better if we make it more clear when the optimizer is expired via change the status in the front site. WDYT @baiyangtx ?

**Comment by baiyangtx** [comment]
> Disply the token id can help us to identifier status of optimzier. It would be better if we make it more clear when the optimizer is expired via change the status in the front site. 

If you want to see a disconnected optimizer on the page, it's a better idea to display it with status. 
I think the token is too low-level information to be displayed on the list page, maybe we can add a detail page, or hover to display some details. WDYT @zhoujinsong @XBaith

**Comment by XBaith** [comment]
> If you want to see a disconnected optimizer on the page, it's a better idea to display it with status.
+1. Currently, AMS optimizer only show the "running" status in the front page, it's a good way to expose more detail for optimizer.

**Comment by tcodehuber** [comment]
![image](https://github.com/apache/amoro/assets/5411862/f3b9dcc8-5c26-488d-97ff-cdfa1ac281ca)
