### ISSUE TITLE
[Improvement] Change GitHub repo names

### ISSUE THREAD

**Issue by justinmclean** [apache/amoro#2700]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

It would be better to drop the "incubator—" from the repo names so that when you become a TLP, they won't need to change.

### How should we improve?

Rename this repo to just "amoro"

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Hi, @justinmclean  thanks a lot for bringing up this improvement.
Changing the repo name can indeed reduce work at graduation, but I'm unsure if this meets the requirements of the ASF Incubator, considering many other repo names of the podlings still include the "incubator-" prefix.

**Comment by justinmclean** [comment]
Over time, we have removed the incubator name from the website and other resources to make less work for Infra and make it easier to become a TLP. It would be easier to fix now I think. Can the PPMC can raise an Infra Jira to fix this?

**Comment by czy006** [comment]
Now Repo Change to Amoro
