### ISSUE TITLE
[Improvement]: clean the resource when optimizer instance expired

### ISSUE THREAD

**Issue by Yao-MR** [apache/amoro#2714]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

when release the optimizer, the amoro will remove the resource in the <db table :resource> and then remove the instance

when the optimizer expired, the amoro will remove the instance and will not remove resouce in the db, which will cause this dirty data,

### How should we improve?

we should flow the step when release the optimzier, when we detect the optimizer instance expired, not only should we remove the optimzier, we also should remove the resource record in the db

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by majin1102** [comment]
Thanks for raising this issue.

Can you point out the influence of this improvement? or what have you encountered.
I think expiring and deleting are somehow different operation
