### ISSUE TITLE
[Subtask]: Add shaded fastjson project

### ISSUE THREAD

**Issue by klion26** [apache/amoro#2719]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### Description

Add shaded fastjson project

### Parent issue

#2628 Add amoro shaded project

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by baiyangtx** [comment]
Could this issue be closed due to shade package has been introduced ? @klion26

**Comment by klion26** [comment]
@baiyangtx yes this can be closed for fastjson shaded has been implemented
