### ISSUE TITLE
[Improvement]: Update issue link to apache

### ISSUE THREAD

**Issue by xleoken** [apache/amoro#2742]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Update issue link to apache

### How should we improve?

-

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by baiyangtx** [comment]
fixed due to https://github.com/apache/amoro/pull/2741
