### ISSUE TITLE
[Improvement]: align term 'transaction' with Iceberg 'snapshot'

### ISSUE THREAD

**Issue by link3280** [apache/amoro#2751]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, snapshots are called transactions both in the codebase and the web UI, but under the hood they're the same 
 for Iceberg users (perhaps some functionalities improvement for mixed formats).

I proposed to rename transactions to snapshots, which is more understandable for new users.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by majin1102** [comment]
There's context for this.

Amoro name transacions on snapshots which are not produced by amoro optimizing....
You could see transactions and optimized two tabs. Both of them consists all snapshots.

It could be discussed furthur if this is necessary
