### ISSUE TITLE
[Feature]: Add Tests for helm chart templates

### ISSUE THREAD

**Issue by lianneli** [apache/amoro#2778]
### Description

Amoro Helm chat templates need Tests for more safety and convinent using.

### Use case/motivation

I need to try templates with --dry-run command, which will get confused since so many templates need to be check. Tests will check most of variables automatically, to make more safety to use.

### Describe the solution

We can use helm-unittest module to finish templates's tests, with standard usage instructions.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tcodehuber** [comment]
@lianneli  Good idea ！ If you would work on this issue, I would really appreciate it.
