### ISSUE TITLE
[Improvement]: Improve the error message for OptimizerGroup scale-out

### ISSUE THREAD

**Issue by klion26** [apache/amoro#2782]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Improve the error message for configure OptimzierGroupconfiguring

For example, if configured the `memory` with `4096m`, it can saved successfully but will pop the below error when `Scale-out`
![企业微信截图_6a273038-296d-464d-b8e5-381a84d12179](https://github.com/apache/amoro/assets/1425623/c78e091c-5eb0-4107-9c58-24684cca136b)

### How should we improve?

IMHO we can improve this:
1. add some check when the configuration save trigged
2. Give some meaningful message if there is something wrong when scale-out

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jiamin13579** [comment]
The new /edit is not directly bound to the implementation, and the "memory" parameter is unique to the local optimizer. The edit operation is not implemented yet, and it is only compatible with multiple memory formats.
