### ISSUE TITLE
[Improvement]: Remove deprecated code that needs to be removed in 0.7

### ISSUE THREAD

**Issue by zhongqishang** [apache/amoro#2787]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Remove `org.apache.amoro.optimizer.common.OptimizerConfig#memorySize` and related code.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by misselvexu** [comment]
/ Assign to me ?

**Comment by zhoujinsong** [comment]
> / Assign to me ?

Assigned.
Thanks for your interest in contributing. Please feel free to tell me if you have any questions about the work.

**Comment by zzzk1** [comment]
Hi @zhoujinsong, I would like to try this.
