### ISSUE TITLE
[Improvement]: Add prefix `amoro-` for optimizer module and keep same with folder

### ISSUE THREAD

**Issue by zhongqishang** [apache/amoro#2802]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

![image](https://github.com/apache/amoro/assets/16421989/8c5c79e1-65f7-4885-bd26-59eca85788d6)

Rename module to prefix with `amoro-` and keep the same name with folder.

### How should we improve?

Rename to

- amoro-optimizer-common
- amoro-optimizer-flink
- amoro-optimizer-spark
- amoro-optimizer-standalone

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongqishang** [comment]
@zhoujinsong @xleoken What do you think about this?

**Comment by zhoujinsong** [comment]
I am +1 with that.

**Comment by tcodehuber** [comment]
+1
