### ISSUE TITLE
[Bug][FLINK]: flink  unified catalog doesn't support mixed_hive 

### ISSUE THREAD

**Issue by Aireed** [apache/amoro#2811]
### What happened?

SQL like this:
```
CREATE CATALOG unifiedCatalog WITH (
'type' = 'unified',
'metastore.url' = 'thrift://xxxx:pppp/unified_catalog'
)

create table if not exists unifiedCatalog.iceberg_test.mh_by_uc_spark_test(
id int,
name string,
dt string,
primary key (id,dt) not enforced
) with ('write.upsert.enabled'='true');
```

we encounted the error 

![image](https://github.com/apache/amoro/assets/8862395/da900d47-7daf-4975-8bc9-f1951775e966)

### Affects Versions

master

### What engines are you seeing the problem on?

Flink

### How to reproduce

```
CREATE CATALOG unifiedCatalog WITH (
'type' = 'unified',
'metastore.url' = 'thrift://xxxx:pppp/unified_catalog'
)

create table if not exists unifiedCatalog.iceberg_test.mh_by_uc_spark_test(
id int,
name string,
dt string,
primary key (id,dt) not enforced
) with ('write.upsert.enabled'='true');
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xieyi888** [comment]
It means this exception occurs because the mixed_hive table hasn't been created or updated?
