### ISSUE TITLE
[Improvement]: Improve the version info about the project

### ISSUE THREAD

**Issue by klion26** [apache/amoro#2813]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, the version info displayed at the topbar shows the version and the build time(such as`Version: 0.7.0-SNAPSHOTCommit Time: 2024-04-18T16:12:39+0800`) this is enough for the release version, but it may not enough when developing.

### How should we improve?

we can include the abbrev property in the version info such as (`Version: 0.7.0-SNAPSHOT(1fa68ab) Commit Time: 2024-04-18T16:12:39+0800`

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Looks like a good improvement, looking forward to seeing it implemented.
