### ISSUE TITLE
[Improvement]: Simplify the quick demo process

### ISSUE THREAD

**Issue by tcodehuber** [apache/amoro#2816]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

* Drop the quick demo image and simplify the existing quick demo
process, depending on the amoro and minio images
* Users can insert/delete/update rows by ams' Terminal page, then we can
trigger minor/major processes instead of installing flink cdc env

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by baiyangtx** [comment]
Could this issue be closed due to #2818 ?

**Comment by zhoujinsong** [comment]
Yes, this can be closed due to :https://github.com/apache/amoro-site/pull/30
