### ISSUE TITLE
[Bug]: Shortcut display disorder in terminal page 

### ISSUE THREAD

**Issue by tcodehuber** [apache/amoro#2837]
### What happened?

As titled:
![image](https://github.com/apache/amoro/assets/5411862/8192d3a2-c04f-4dca-af57-e329df28b57a)

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jiamin13579** [comment]
I want to try
