### ISSUE TITLE
[Improvement]: Add skip-trino-build profile

### ISSUE THREAD

**Issue by xleoken** [apache/amoro#2853]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

It not friendly for users to use `mvn clean package -DskipTests -pl '!amoro-mixed-format/amoro-mixed-format-trino'` to build the amoro project. Add a new `skip-trino-build` profile to improve the build command.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Thanks a lot for bringing up this improvement.

The old maven command is indeed quite complex to use.
But actually, most of the time, we do not need to build the `amoro-mixed-format-trino` module as it dependent on a different JDK version.
So how about adding a profile named `build-mixed-format-trino` and inactive it by default?

So most of the time, you can execute `mvn clean package` to package all modules except `build-mixed-format-trino`.
And you can execute `mvn clean package -Pbuild-mixed-format-trino -Ptoolchain` to package all modules.

**Comment by xleoken** [comment]
@zhoujinsong you are right, I'll think about it again.
