### ISSUE TITLE
[Subtask][Feature]: Display Apache Hudi metadata in AMS Dashboard

### ISSUE THREAD

**Issue by baiyangtx** [apache/amoro#2861]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### Description

- Display Hudi tables in HadoopCatalog and HiveCatalog
- Show Schema and properties in Table Detail Page
- Show Hudi timeline and commit information in Table Snapshot Page
- Show Hudi compact and clean instant in Table Optimizing Page 
- Statistic Hudi parititions and files and display them on Table Files Pages

### Parent issue

#220 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Thanks for bringing this up, looking forward it!
