### ISSUE TITLE
[Improvement]: Support metrics related settings for helm charts

### ISSUE THREAD

**Issue by tcodehuber** [apache/amoro#2898]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

There are no metrics related settings in values.yaml, which is useful in our env. 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jiamin13579** [comment]
Let me try

**Comment by tcodehuber** [comment]
> Let me try

Assigned it to you, thanks for your work.
