### ISSUE TITLE
[Bug]: Frontend error when clicking Cancel Process button

### ISSUE THREAD

**Issue by tcodehuber** [apache/amoro#2917]
### What happened?

![image](https://github.com/apache/amoro/assets/5411862/33b69a0b-f4f5-4324-bd17-38cd56cf4a10)

### Affects Versions

master

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
cc @zhangmo8 @minteliuwm

**Comment by zhangmo8** [comment]
Hi @tcodehuber .Think you for you feedback

It's worked in my local. Maybe you should sync you code to latest version

<img width="1460" alt="image" src="https://github.com/apache/amoro/assets/43628500/70172bcc-151f-447c-ba8c-7408039f994f">
