### ISSUE TITLE
[Bug]: The number of optimize records on the snapshots tab does not match the number of records on the optimizing tag page.

### ISSUE THREAD

**Issue by Aireed** [apache/amoro#2937]
### What happened?

catalog: unifiedSessionCatalog
metastore: hms
table-format: mixed-hive

optmizing Tab:
![image](https://github.com/apache/amoro/assets/8862395/93a7767e-c4b9-42f8-abf0-a3e1e480656d)

snapshots tab:
![image](https://github.com/apache/amoro/assets/8862395/53ec3cb8-e104-40fb-82af-a85e873b7506)
![image](https://github.com/apache/amoro/assets/8862395/2f01d8e9-974a-43f8-9ea0-29f0f3a9c6c3)

### Affects Versions

master

### What table format are you seeing the problem on?

Mixed-Hive

### What engines are you seeing the problem on?

AMS, Optimizer

### How to reproduce

1、upgrade a hive table to mixed-hive
2、crud the table

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
@Aireed Thanks for reporting.

At this stage, the committing phase of Mixed-Hive table self-optimizing may indeed generate multiple snapshots. We can try to optimize this in future versions, but for now, it is expected behavior.
