### ISSUE TITLE
[Improvement]: ams dashboard fully support i18n

### ISSUE THREAD

**Issue by yimlin** [apache/amoro#2941]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

so far,  the i18n support of ams dashboard is very limited: Menu items Only.

### How should we improve?

All views should support i18n.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chouchouji** [comment]
Can this issue be assigned to me?

**Comment by tcodehuber** [comment]
> Can this issue be assigned to me?

Absolutely yes.

**Comment by chouchouji** [comment]
> > Can this issue be assigned to me?
> 
> Absolutely yes.

Thanks you! I will complete it in recent days.
