### ISSUE TITLE
[Improvement]: Move charts and docker to deploy folder

### ISSUE THREAD

**Issue by xleoken** [apache/amoro#2954]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

As we known, there is a correlation between `charts` and `docker` folder, so it is more appropriate to put them together, like https://github.com/apache/dolphinscheduler/tree/dev/deploy

```
develop/
  -- charts/
      --amoro
  -- docker
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xleoken** [comment]
hi @zhoujinsong @czy006, what are your thoughts?

**Comment by zhoujinsong** [comment]
Docker and Helm are both commonly used tools in current software development. However, they do not have an inherent relationship. It is common to find them placed independently in many projects, often in the root directory, to make it easier for users to locate them：

- https://github.com/apache/incubator-streampark
- https://github.com/apache/kyuubi

**Comment by xleoken** [comment]
make sense, close this minor issue.
