### ISSUE TITLE
[Improvement]: Integrate the log records of debug, info, and error into one file

### ISSUE THREAD

**Issue by xleoken** [apache/amoro#2955]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

It is not a good practice to record the log records of debug, info, and error separately in different files, and there is a contextual linking relationship between them.

```
[dcadmin@dcadmin-work logs]$  ll
total 179988
-rw-rw-r-- 1 dcadmin dcadmin         0 Jun 21 16:31 amoro-metrics.log
-rw-rw-r-- 1 dcadmin dcadmin         0 Jun 21 16:31 ams-debug.log
-rw-rw-r-- 1 dcadmin dcadmin  35377462 Jun 21 17:51 ams-error.log
-rw-rw-r-- 1 dcadmin dcadmin 148887752 Jun 21 17:51 ams-info.log
-rw-rw-r-- 1 dcadmin dcadmin         0 Jun 21 16:31 app.log.err
-rw-rw-r-- 1 dcadmin dcadmin     25485 Jun 21 17:51 gc.log.0.current
``` 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by daragu** [comment]
i can take this :)

**Comment by zhoujinsong** [comment]
As far as I know, the `ams-info.log` file now also includes warning and error logs. Similarly, the `ams-debug.log` file contains all logs(disable by default).

**Comment by xleoken** [comment]
@daragu thanks for taking this, but we are still discussing this issue.
