### ISSUE TITLE
[Improvement]: Change Source Code link to Quick Start

### ISSUE THREAD

**Issue by xleoken** [apache/amoro#2957]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

It seems better to change `Source Code` to `Quick Start` link.

![image](https://github.com/apache/amoro/assets/95013770/25de81b7-c094-482a-90ac-2f4470afe596)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xleoken** [comment]
cc @zhoujinsong

**Comment by zhoujinsong** [comment]
Good point, I will change it.
