### ISSUE TITLE
[Improvement]: Eliminate AMS Full GC impactions deriving from local terminal clean spark context

### ISSUE THREAD

**Issue by nicochen** [apache/amoro#2968]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

We experienced and suffered from AMS full GC for a long period. we dig into this case and finally found out  local spark session terminal triggers java.lang.System.gc() every 30 minutes  to clean contexts. As arthas stack traces as shown below:
![image](https://github.com/apache/amoro/assets/4648576/198782c3-0353-4c38-83c4-a61c2ccbaceb)

### How should we improve?

For external kyuubi session terminal, there is no need to revises anything. The problem is only related to local session which is embedding into AMS itself. Simply add  config 'spark.cleaner.referenceTracking' = 'false' to solve the problem.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by nicochen** [comment]
@czy006  Due to my working network issue, the same issues seem to been wrongly submitted twice. Sry about that. This one is duplicated with #2969 and has already been merged. The fix logic is same. I will close this issue ad duplicated.

**Comment by nicochen** [comment]
Duplicated with https://github.com/apache/amoro/issues/2969. Closed

**Comment by czy006** [comment]
@nicochen thanks for your callback
