### ISSUE TITLE
[Improvement]: Refresh the catalog list after remove one catalog

### ISSUE THREAD

**Issue by xleoken** [apache/amoro#2996]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Refresh the catalog list after remove one catalog.

![image](https://github.com/apache/amoro/assets/95013770/2c32a86a-40da-422b-aebd-671c35fc3811)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xleoken** [comment]
cc @zhoujinsong, need someone familiar with the ui to solve this problem.

**Comment by tcodehuber** [comment]
> cc @zhoujinsong, need someone familiar with the ui to solve this problem.

@xleoken Plz refer to PR: #2998
