### ISSUE TITLE
[Improvement]: Add Paimon Table Consumer Infos In Ams Dashboard

### ISSUE THREAD

**Issue by czy006** [apache/amoro#3054]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

after #3027 for paimon consumer,we need dashboard have some consumer info to know consumer paimon table what next snapshot

### How should we improve?

 ![image](https://github.com/user-attachments/assets/c83a1c5d-7205-4822-a745-c8f080c15c55)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Liammcl** [comment]
I am willing to submit a PR

**Comment by Liammcl** [comment]
I am willing to submit this PR

**Comment by zhoujinsong** [comment]
Hi, I am not sure about placing the consumer information with the branch and tag is a good suggestion.

Consumer information appears to be completely new metadata, perhaps we can consider adding an additional TAB to display it. Alternatively, if it is closely related to the snapshot, we could also consider highlighting it in the snapshot list.

**Comment by Liammcl** [comment]
sure, Where do you think it should be placed ?

**Comment by czy006** [comment]
> Hi, I am not sure about placing the consumer information with the branch and tag is a good suggestion.
> 
> Consumer information appears to be completely new metadata, perhaps we can consider adding an additional TAB to display it. Alternatively, if it is closely related to the snapshot, we could also consider highlighting it in the snapshot list.

In this section, you can view the final rendering, which is part of the Snapshot metadata, and if there is a better place to display it, we can modify it at any time cc @zhoujinsong
