### ISSUE TITLE
[Improvement]: Improve the efficiency for RESTAPI of optimizing-processes

### ISSUE THREAD

**Issue by klion26** [apache/amoro#3066]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

as the title saied
the endpoint is `catalogs/{catalog}/dbs/{db}/tables/{table}/optimizing-processes`

### How should we improve?

backgroud and maybe the solution can read the [doc](https://docs.qq.com/doc/DQU9sZ2RsdmRYSE1V)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klion26** [comment]
1. remove the `ServerCatalog#tableExists(db, table) ` in `TableController#getOptimizingProcesses` because we can reuse the table load logic in the following logic
2. push the `offset` and `limit` in `mapper#selectOptimizingProcesses`(`MixedAndIcebergTableDescriptor#getOptimizingProcessesInfo`) to db (this can limit the items retrieved from db)

**Comment by klion26** [comment]
The initial idea is to implement 1 and 2 above first, and then implement 3 and the front end together. what do you think about this? thanks @zhoujinsong @majin1102

**Comment by zhoujinsong** [comment]
Thanks for pushing this improvement forward! @klion26 

> remove the ServerCatalog#tableExists(db, table)  in TableController#getOptimizingProcesses because we can reuse the table load logic in the following logic

I am okay with this change, we will load the table in following steps, we chan check this in that phrase.

> push the offset and limit in mapper#selectOptimizingProcesses(MixedAndIcebergTableDescriptor#getOptimizingProcessesInfo) to db (this can limit the items retrieved from db)

Yes, we should limit the result set return by database as we may have a large history records.

> add format info when calling this rest API, so that MixedAndIceberg can avoid loading the table from external catalog(this is to be confirmed）

I am not sure if we still need to load the table, if yes we can get the table format from the loaded table.
