### ISSUE TITLE
[Bug]: Error in docker-compose.yaml of quick start

### ISSUE THREAD

**Issue by ideal** [apache/amoro#3086]
### What happened?

In https://amoro.apache.org/quick-start/ , there are two errors:

1. the docker image `apache/amoro` does not exists:
<img width="485" alt="截屏2024-08-08 17 25 17" src="https://github.com/user-attachments/assets/d3011fa0-679f-4971-8e10-3caa58077c52">

2. the network alias `warehouse.minio` in services appears in two places, which should be wrong.

### Affects Versions

all

### How to reproduce

See https://amoro.apache.org/quick-start/ .

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
Thanks for reporting this bug!

There is no latest tag for the `apache/amoro` image, which should be fixed.

**Comment by ideal** [comment]
@zhoujinsong how about another problem?

> 2. the network alias warehouse.minio in services appears in two places, which should be wrong.

**Comment by tcodehuber** [comment]
> @zhoujinsong how about another problem?
> 
> > 2. the network alias warehouse.minio in services appears in two places, which should be wrong.

@ideal Would you please fix this issue and make a PR for the project `https://github.com/apache/amoro-site`

**Comment by ideal** [comment]
> > @zhoujinsong how about another problem?
> > > 2. the network alias warehouse.minio in services appears in two places, which should be wrong.
> 
> @ideal Would you please fix this issue and make a PR for the project `https://github.com/apache/amoro-site`

OK.
