### ISSUE TITLE
[Improvement]: Support AMS Metric Reporter Json Format Send to Kafka

### ISSUE THREAD

**Issue by czy006** [apache/amoro#3092]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

For now we only support prometheus for collecting Amoro monitoring data. New implementation users can configure another policy to report data as JSON to Kafka for use by external systems

### How should we improve?

- Add **amoro-metrics-kafka** Model
- implement metrics to json formate
- send metrics json to kafka,set metric properties in ams **metric-reporters.yaml**

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by huyuanfeng2018** [comment]
-1 for this proposal.
In my opinion, reporting to kafka is a very specific requirement. In actual scenarios, metric is often handed over to professional monitoring components, such as Prometheus,jmx, etc.
However, kafka is obviously not here. If really need kafka, can just implement a plug-in yourself. I don't think amoro needs to integrate these capabilities.

**Comment by czy006** [comment]
> -1 for this proposal. In my opinion, reporting to kafka is a very specific requirement. In actual scenarios, metric is often handed over to professional monitoring components, such as Prometheus,jmx, etc. However, kafka is obviously not here. If really need kafka, can just implement a plug-in yourself. I don't think amoro needs to integrate these capabilities.

Amoro was designed with Rich Plugins as one of its capabilities

As  Metric is concerned, it is just one of the metric reporting implement, and I believe it has no intrusive impact on Amoro

From a user perspective, there seems to be no other option when they don't want to deploy an additional set of **Prometheus + Granfna**
