### ISSUE TITLE
[Bug]: Optimization state blocking in planning

### ISSUE THREAD

**Issue by rfyu** [apache/amoro#3111]
### What happened?

The exception thrown by the `org.apache.amoro.server.optimizing.OptimizingQueue#planInternal` was not handled, and the catch content will also cause an exception because the jdbc connection is not obtained. So the table is always in the running state.
![image](https://github.com/user-attachments/assets/dbf35b69-e821-4c07-a16e-36c67fe255e8)

### Affects Versions

master

### What table formats are you seeing the problem on?

Iceberg

### What engines are you seeing the problem on?

AMS

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
The root cause seems to be that AMS failed to update the optimizing status after planning because of a lack of database connection.

I think we cannot update the status to pending if the connection issue is not recovered.
I can accept the status error as if the table can keep planning.
