### ISSUE TITLE
[Improvement]: Move failOnNoGitDirectory of git-commit-plugin to profile

### ISSUE THREAD

**Issue by klion26** [apache/amoro#3125]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

In  #3042 we add configuration `failOnNoGitDirectory` for git-commit-plugin so that it would not block the release process, but in the normal process, it would not fail even if there is not git dir, we want it fail if there is not git dir in the normal case.

### How should we improve?

move the configuration to profile, and enable it when release

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongqishang** [comment]
@klion26 I want to ask why it needs to fail when there is no git folder? 
A very common scenario is to download the zip file directly from github. It will not contain the .git folder. 
In this case, the compilation will fail directly, which is not user-friendly.

**Comment by zhongqishang** [comment]
In flink[1].

Although iceberg sets the value to `true`, I can see from the original comment that the compilation does not fail.[2]

[1]: https://github.com/apache/flink/blob/master/flink-runtime/pom.xml#L353
[2]: https://github.com/apache/iceberg/pull/5236#discussion_r917441606

**Comment by klion26** [comment]
@zhongqishang  Currently, every build (normal and release) will not fail even if there is no .git folder. The changes here are to fail the build if the .git folder does not exist, and add a configuration to make it not fail. The former way is what we want in local development mode, and the latter way (not failing) is used for the release process.

In flink, I think it was missed by the original contributor[1]

[1] https://github.com/apache/flink/pull/12941#issuecomment-663617091
