### ISSUE TITLE
[Improvement]: OOTB grafana dashbord json

### ISSUE THREAD

**Issue by Mrzyxing** [apache/amoro#3131]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

We got an excellent feature of prometheus metrics exporter in version 0.7, and further more, we can give user more convenient tools for out-of-the-box monitor dashboard such as template of grafana.

### How should we improve?

As mentioned below, maybe a grafana json file or template id is a good ways for user to build a dashboard.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tcodehuber** [comment]
@jiamin13579 Would you plz work on it?

**Comment by jiamin13579** [comment]
> @jiamin13579 Would you plz work on it?

Glad to have it done
