### ISSUE TITLE
[Improvement]: Filter out the CodecPool log in the optimizer log

### ISSUE THREAD

**Issue by klion26** [apache/amoro#3145]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, there will be a lot of logs for compressor/decompressor such as below.

![image](https://github.com/user-attachments/assets/8755df70-b0bf-4c66-9381-3c4aa9bf0573)

### How should we improve?

We can filter out these logs by modifying the log4j property

Seems currently only the log4j property of local optimizer was managed by Amoro, so we only need to change the log4j property for local optimizer, and let the flink/spark to user(maybe we can add some docs)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klion26** [comment]
@zhoujinsong @baiyangtx what do you think about this feature, if this is valid I can contribute it later.

**Comment by czy006** [comment]
+1
