### ISSUE TITLE
[Subtask]: Implement health score calculation for tables

### ISSUE THREAD

**Issue by MarigWeizhi** [apache/amoro#3180]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### Description

We would like to add a health score feature for our tables.   
The health score will reflect the overall state of the table.   

The health score should be calculated based on the following factors:

* Average Data File Size (40%)
* Equality Delete Data Ratio (40%)
* Position Delete Data Ratio (20%)   

#### Parameter Definition
* **averageDataFileSize**：`dataFilesSize / dataFiles`, excluding delete file
* **eqDeleteRatio**： `eqDeleteRecords / dataRecords`
* **posDeleteRatio**： `posDeleteRecords / dataRecords`
* **targetSize**:  Target size of data file , Default: 128 MB
* **minTargetSize**: `targetSize * minTargetSizeRatio`, Average data file sizes below this value are considered unhealthy, Defalult:  96 MB
* **majorDuplicateRatio**：Default: 0.1
* **minorLeastFileCount**:  Default: 12
* **eqDeleteRatioThreshold** ：equals  `majorDuplicateRatio`，If eqDeleteRatio exceeds this value, the penalty item is deducted in full
* **posDeleteRatioThreshold** ：equals   `2 * majorDuplicateRatio`， If posDeleteRatio exceeds this value, the penalty item is deducted in full
* **tablePenaltyFactor**: Small tables have very little impact on performance, so there is only a small penalty, and in the special case if the number of table files is less than or equal to 1, tablePenaltyFactor equals 0 , i.e., the table is considered to be perfectly healthy
$tablePenaltyFactor = \frac{MIN(dataFiles, minorLeastFileCount)}{minorLeastFileCount} * \frac{MIN(dataFilesSize,minTargetSize)}{minTargetSize}$

#### Formula
$$HealthScore = 100 - tablePenaltyFactor   *（ 40 * smallFilePenaltyFactor +  40 * eqDeletePenaltyFactor  +  20 * posDeletePenaltyFactor ) $$ 

#### Full Formula:  
$$HealthScore = 100  -  tablePenaltyFactor * ( 40 * (1-\frac{MIN(averageDataFileSize, minTargetSize )}{minTargetSize} ) + 40 * \frac{MIN(eqDeleteRatio, eqDeleteRatioThreshold)}{eqDeleteRatioThreshold}  + 20 *\frac{MIN(posDeleteRatio,posDeleteRatioThreshold)}{posDeleteRatioThreshold} )$$

If you have suggestions or ideas, please feel free to discuss them.

### Parent issue

https://github.com/apache/amoro/issues/2532

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by majin1102** [comment]
Two questions:
1. How a specific number tells the real action need to be done.
2. How to extend this feature to multiple formats, or this is only for Iceberg, then shall consider how to costomize the keyvalues presented here
