### ISSUE TITLE
[Improvement]: OptimizerController decoupling to OptimizerGroupController

### ISSUE THREAD

**Issue by czy006** [apache/amoro#3195]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

OptimizerController now have OptimizerGroup method,We hope to clarify the responsibilities of each component. When using external containers, we do not need to additionally host them on Amoro Optimizer. 

### How should we improve?

- move OptimizerController optimizerGroup Methods to OptimizerGroupController
- web ui role to OptimizerController and OptimizerGroupController

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by majin1102** [comment]
This seems quite reasonable!

**Comment by czy006** [comment]
> This seems quite reasonable!

It is a part of #3038, and I will continue to follow up this part of work in the future
