### ISSUE TITLE
[Bug]: catalog table filtering problem

### ISSUE THREAD

**Issue by w724457655** [apache/amoro#3196]
### What happened?

We have created two catalogs, zj_catalog and error_catalog, during our usage.  Some tables in zj_catalog are in a pending state if no catalog selection is made.  However, when zj_catalog is selected, there are no corresponding tables in pending, and searching for the tables directly is also unsuccessful.  Moreover, these tables have not been planned or executed, and they are stuck in the pending state.
![image](https://github.com/user-attachments/assets/b0ccacf0-5535-452b-8f69-eb38c39321c8)
![image](https://github.com/user-attachments/assets/340f0b1e-576c-499e-8b2e-9aefecbfc34f)

### Affects Versions

0.7.0

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majin1102** [comment]
Thanks to feed back.

First, what you searched is optimizer group, not catalog, please pay attention on the hint of searchbox

Second, I believe the long pending status is a scheduling issue which has been discussed in some online discussions.  I raise a PR to fix the issue. I suggest you to take a review and try if this could solve your problem after merged:

https://github.com/apache/amoro/pull/3203
