### ISSUE TITLE
[Improvement]: Improve optimizing page refresh logic

### ISSUE THREAD

**Issue by majin1102** [apache/amoro#3205]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Now optimizing page has three search boxes:

- Optimizer Group
- DB Name
- Table Name

For DB and table name, the search would occur at every single texting which make it almost unavailable when the page is too large(the backend returns all pages):

![image](https://github.com/user-attachments/assets/c987a115-e978-48b2-af8e-4e46fdb2b807)

I suggest to add a refresh button after table search box and the page refreshes only after clicking refresh botton including optimizer group for uniformity.

The buttom should be grey and unavailble for no search conditions.

### How should we improve?

This is a total frontend improvement

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangmo8** [comment]
Maybe it would be more appropriate to call it a search button rather than a refresh button.

**Comment by majin1102** [comment]
> Maybe it would be more appropriate to call it a search button rather than a refresh button.

LGTM
