### ISSUE TITLE
[Bug]: optimizing Tab paging display error

### ISSUE THREAD

**Issue by huyuanfeng2018** [apache/amoro#3218]
### What happened?

<img width="1700" alt="image" src="https://github.com/user-attachments/assets/dede95fa-ebf8-4a98-a071-c6678187da75">
No matter how many items are selected to be displayed per page, there will only be one page in the end.

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by huyuanfeng2018** [comment]
<img width="891" alt="image" src="https://github.com/user-attachments/assets/f65b1433-9c57-4dbd-abe7-e6f499bbfd8b">
ams returns total value error

**Comment by majin1102** [comment]
I suggest keeping an eye on this PR merged recently:

https://github.com/apache/amoro/pull/2914

This modified a lot

**Comment by klion26** [comment]
@huyuanfeng2018 this may be the problem introduced by #2914, I'll submit a patch for this. the total number is correct, but the value is not right. this was merged into 0.8-SNAPSHOT(not in 0.7 branch), so we don't need to backport this to 0.7-branch if we don't want backport #2914 back.

**Comment by klion26** [comment]
@huyuanfeng2018 I've filed a pr(#3231) try to fix this problem, could you please check whether this fix your problem thanks.
