### ISSUE TITLE
[Improvement]: Typos in en.ts and zh.ts

### ISSUE THREAD

**Issue by zhongqishang** [apache/amoro#3251]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

- Use camel case naming
	- addgroup -> addGroup
	- ...
- Typo `partiton` -> `partition`
- Typo `welecomeTip` -> `welcomeTip`
- Duplicate `optimizergroup`
...

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chouchouji** [comment]
Can you make a detailed list? I will submit a pr to fix.
