### ISSUE TITLE
[Bug]: The millisecond-level cost time cannot be displayed normally on the page

### ISSUE THREAD

**Issue by zhongqishang** [apache/amoro#3287]
### What happened?

![image](https://github.com/user-attachments/assets/6fd2df6f-5b4c-46ab-9757-6b7dbfe03894)

We can keep a maximum of 2 time units.

like : 
- 10 ms
- 10 s 10 ms
- 1 min 10 s
- 1 h 10min

### Affects Versions

master

### What table formats are you seeing the problem on?

Iceberg

### What engines are you seeing the problem on?

AMS

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Dudis2k** [comment]
I'm willing to fix this bug as this being labelled good first issue labelled, Please assign this issue to my id- Dudis2k

**Comment by ihadoop** [comment]
@Dudis2k  Have you finished ?

**Comment by zhongqishang** [comment]
> @Dudis2k Have you finished ?

@ihadoop Feel free to open PR.
