### ISSUE TITLE
[Improvement]: Change the color of the status icon in the running state

### ISSUE THREAD

**Issue by zhongqishang** [apache/amoro#3288]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

![image](https://github.com/user-attachments/assets/5f25cbeb-670a-4969-ba1d-44601e11a305)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongqishang** [comment]
@nafisreza I think we should just replace `ACTIVE` with `RUNNING`.

Refer to : https://github.com/apache/amoro/pull/3173

**Comment by nafisreza** [comment]
Thank you. I have added both status and their colors.
