### ISSUE TITLE
[Feature]: Support OSS for iceberg in InternalCatalog

### ISSUE THREAD

**Issue by shouwangyw** [apache/amoro#3301]
### Description

Add OSS storage type, support OSS for iceberg in InternalCatalog

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Nice catch!
I believe this feature can improve Aliyun's user experience.
