### ISSUE TITLE
[Bug]: get signature check error when upload catalog config files

### ISSUE THREAD

**Issue by Aireed** [apache/amoro#3308]
### What happened?

![image](https://github.com/user-attachments/assets/45966824-c0e9-4a55-9396-ea9411ca358e)
got signature check error when upload files, for the request lack the x-request-source 

### Affects Versions

master

### What table formats are you seeing the problem on?

Iceberg

### What engines are you seeing the problem on?

AMS

### How to reproduce

upload files in catalog creation page

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by czy006** [comment]
cc @mansonliwh
