### ISSUE TITLE
[Improvement]: Optimize excessive database access in CommonUnifiedCatalog

### ISSUE THREAD

**Issue by zhangwl9** [apache/amoro#3330]
### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, some `databaseExists` checks in `CommonUnifiedCatalog` is redundant because the logic can be coverd by the subsequent logic(such as `CommonUnifiedCatalog#createDatabase`, `CommonUnifiedCatalog#dropDatabase`) , and the `databaseExists` checks will make a call to the external catalog(eg HiveMetaStore), which may be time-consuming.

### How should we improve?

Remove redundant 'databaseExists'  checks in `CommonUnifiedCatalog`  to improve performance.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klion26** [comment]
Thanks for filing the issue, seems the `databaseExists` call in `createDatabase` and `dropDatabase` can be suppressed by the subsequent logic, but the `databaseExists` in `listDatabase` seems can not remove directly, we may need to make sure the `FormatCatalog#listTables` respect the java doc and then can remove the `databaseExists`

**Comment by zhangwl9** [comment]
> Thanks for filing the issue, seems the `databaseExists` call in `createDatabase` and `dropDatabase` can be suppressed by the subsequent logic, but the `databaseExists` in `listDatabase` seems can not remove directly, we may need to make sure the `FormatCatalog#listTables` respect the java doc and then can remove the `databaseExists`

 We add exception handling for NoSuchDatabaseException in 'HudiHadoopCatalog#listTables' and 'MixedCatalog#listTables' methods which are called in 'FormatCatalog#listTables'  to eliminate the redundancy of 'databaseExists' in 'CommonUnifiedCatalog#listTables'.

**Comment by zhangwl9** [comment]
@majin1102 @czy006 could you please take a look at this when you're free, thanks

**Comment by zhangwl9** [comment]
@zhoujinsong  @klion26 thanks for the review and merging!
