### ISSUE TITLE
[Feature][AMS]: Add overview page in AMS dashboard 

### ISSUE THREAD

**Issue by zhoujinsong** [apache/amoro#405]
### Description

We need an overview page in AMS dashboard to disply the summary information and metrics of Arctic.

### Use case/motivation

Add an overview page in AMS dashboard to disply the summary information and metrics of Arctic.

### Describe the solution

- Collect summary information and metrics in AMS.
- Add an overview page in AMS dashboard and disply the information with chart and table list etc.

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by majin1102** [comment]
visual design for overview page:
![image](https://user-images.githubusercontent.com/5731171/196355547-afc6b8d5-c296-4762-9a16-5c5bcc02a14b.png)
including:

- overview statistics：table/catalog count, space size, optimizing resources
- optimizing brief：resource usage curve, optimizing table list
- table space brief: space size curve, table size list

**Comment by XBaith** [comment]
Hi @zhoujinsong @majin1102 , have you considered stats for Iceberg table health? For example, estimate the time cost of a simple query, if it is greater than a reasonable time, then the table is probably an unhealthy table. Then Arctic can directly tell the users which tables are not suitable for reading, instead of giving us feedback when the query is too slow.

**Comment by zhoujinsong** [comment]
@XBaith , I agree that it will be very useful if we can tell users if iceberg tables are healthy.
As far as I can see, the unhealthy conditions of the table may be：

- Too many small files
- Too many delete data

And yes, Arctic is trying to help tables avoid the problems above.

**Comment by XBaith** [comment]
> 

@zhoujinsong Correct. But for the native iceberg format, "eq-delete rate" is also an important indicator. We can calculate `eq-delete rate` by `total-eq-delete-records` / `total-records`. On the iceberg JMM benchmark, query performance may be unacceptable when `eq-delete` is greater than `0.6` (estimated value)

**Comment by MarigWeizhi** [comment]
I've updated the visual design of the overview page  
![VisualDesign](https://github.com/user-attachments/assets/665ed2c9-6b44-42ec-a307-88abeb6148f8)  

including:

overview statistics：table/catalog count, space size, optimizing resources  
Table Format statistics  
Optimizing Status statistics  
Unhealth Tables  
Latest Operations

**Comment by tcodehuber** [comment]
Can we add some charts to display the trend of overall data(data size, file count)?
