### ISSUE TITLE
[Feature]: Trino support DDL

### ISSUE THREAD

**Issue by shidayang** [apache/amoro#657]
### Description

Make trino supporting ddl for arctic.

### Use case/motivation

Use can create table with trino like:
create table tb(
a int,
b string,
primary key(a)
)with(
xx=xx
)
### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shidayang** [comment]
cc @liyubin117

**Comment by liyubin117** [comment]
I will implement the feature as soon as possible.
