### ISSUE TITLE
[Bug]: Optimize transaction should be not shown under transaction tab in AMS Dashboard

### ISSUE THREAD

**Issue by zhoujinsong** [apache/amoro#689]
### What happened?

Optimize transaction should be not shown under transaction tab in AMS Dashboard

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### How to reproduce

1. Create an iceberg table
2. Write into the new iceberg table
3. Wait for optimize operation completed
4. Show the table transaction and you will got 2 witch one of it is procedured by optimize process

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
cc @hameizi

**Comment by hameizi** [comment]
i will fix this in #701
