### ISSUE TITLE
[Bug]: Optimize task hang on Prepared when throw new pos-delete ValidationException

### ISSUE THREAD

**Issue by xxubai** [apache/amoro#922]
### What happened?

Optimize task hang on `Perpared`  statu forever cause `IcebergOptimizeCommit` dosen't catch the ValidationException:
```
ValidationException.check(
    Arrays.stream(deleteFiles).noneMatch(deleteFile -> deleteFile.content() == FileContent.POSITION_DELETES),
    "Cannot commit, found new position delete for replaced data file: %s", dataFile);
```
, and keep throwing the error `unexpected commit error `

### Affects Versions

master/0.4.x

### What engines are you seeing the problem on?

AMS, Optimizer

### How to reproduce

1. keep writing a table on real-time
2. optimize the table
3. trigger commit

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
@XBaith I want to know the reason why you think this error can be ignored.
This error occurs when the rewritten data is deleted by the new Positional delete file. It should not occur when written by Flink.
Do you have set the table property `write.metadata.metrics.default=all`?

**Comment by zhoujinsong** [comment]
By the way, you seems to have to drop the planed tasks and begin to a new round of optimize planning when you meeting this error.

**Comment by majin1102** [comment]
> @XBaith I want to know the reason why you think this error can be ignored. This error occurs when the rewritten data is deleted by the new Positional delete file. It should not occur when written by Flink. Do you have set the table property `write.metadata.metrics.default=all`?

He calls an Iceberg optimize command as I see, which causes self-optimizing rewrite failed for conflicting detected.

This error could be ignored and re-planning would be nice. cc @wangtaohz consider re-planning for this situation?

**Comment by majin1102** [comment]
Thanks for feeding back, we could talk about this exception handing deeper

**Comment by XBaith** [comment]
> @XBaith I want to know the reason why you think this error can be ignored. This error occurs when the rewritten data is deleted by the new Positional delete file. It should not occur when written by Flink. Do you have set the table property `write.metadata.metrics.default=all`?

I did, but sometimes the preporty is not working.

**Comment by XBaith** [comment]
> By the way, you seems to have to drop the planed tasks and begin to a new round of optimize planning when you meeting this error.

excatly, so I want to clear the optimize task and do next operations
