### ISSUE TITLE
[Improvement][Hive]: When I set base.hive.auto-sync-data-write is true, optimize task executes slowly

### ISSUE THREAD

**Issue by hzluting** [apache/amoro#952]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

I set base.hive.auto-sync-data-write is true. 
The arctic table will refresh when optimize plan starts, there is hive data sync work needed to do, and this costs a lot of time.
Now, the optimize plan is a single thread, so costing too much time in the optimize plan will block the optimizer poll task.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
@hzluting Can you provide the change in time taken by optimizing plan with this parameter on?

The check process will go through the properties of all the hive partitions, which will be somewhat expensive, but I'm not sure how much extra overhead it will incur in a real-world scenario.

**Comment by hzluting** [comment]
> @hzluting Can you provide the change in time taken by optimizing plan with this parameter on?
> 
> The check process will go through the properties of all the hive partitions, which will be somewhat expensive, but I'm not sure how much extra overhead it will incur in a real-world scenario.

OK, I have an optimizing group that contains 4 tables, and a table has more than 700 optimizing tasks. Once I set "base.hive.auto-sync-data-write" to be true for all 4 tables, this table can't do optimizing anymore. And I print the plan thread stack, it is running and always waiting to get files from HDFS.
I guess the optimizing plan refreshes tables too frequently, and it maybe causes great pressure on the HDFS.
